src/Pipes/Prelude.hs

Made toListM less lazy based on https://github.com/Gabriel439/Haskell-Pipes-Library/issues/138

Changed toListM to be less lazy to prevent stack space overflows

---

pipes.cabal

Build matrix: http://matrix.hackage.haskell.org/package/pipes#GHC-7.0/pipes-4.1.4
I've revised the latest releases: https://hackage.haskell.org/package/pipes-4.1.5/revisions/

Needs GHC >= 7.2 due to usage of Trustworthy

---

src/Pipes/Prelude.hs

I think a pipe to control stricness has been missing. One based on `($!!)` would be nice as well, but that is probably not enough in order to add `deepseq` as a new dependency.

Add a "seq"-based evaluation pipe to Prelude

---

src/Pipes/Prelude.hs

This gives pipelines a chance to hand the failing element downstream:
``` haskell
runEffect $ for (each [1..10] >-> (P.takeWhile (<4) >>= yield >> cat)) $
liftIO . Prelude.print
```
Otherwise, there is no way to make use of that element, neither to drop it, consume it, nor re-yield it.

Change takeWhile to return the failing element

---

src/Pipes/Prelude.hs

I was writing a replica of Pipes.Prelude for the obvious variant of `FreeT ((,) a) m r` and it was irritating that this could not be found.  See the dumb comments on the parallel function at
https://github.com/michaelt/streaming/blob/c3ee6d89c2a019a1b198b73edbd37e4d52cf3f3d/Streaming/Prelude.hs#L715
and the corresponding comments on 'next' and 'uncons'
https://github.com/michaelt/streaming/blob/c3ee6d89c2a019a1b198b73edbd37e4d52cf3f3d/Streaming/Prelude.hs
It is a slightly different issue, but it was seeming to me that it might be easy to get 'interoperation' for the Producer, Conduit.Source, IOStreams.InputStream types if they all exported a 'next' or 'uncons' .  The other natural way of 'translating' is via a natural fold or church encoding. But the 'fold' concept is in all these …

add unfoldr

---

src/Pipes/Prelude.hs
src/Pipes/Tutorial.hs

* It has no dependencies other than pipes ones.
* It is useful on its own, without regard to MVC package.
The only downside I can think of is loop being a very common name (e.g. first patch
in the series). OTOH, Pipes.Prelude has other common names (e.g. map) and requires careful
imports even now.

Add loop function from MVC

---

src/Pipes/Prelude.hs

This is not important but for some reason, the use of the imported `replicateM_` for `take` and `drop` impedes optimization.  I noticed this fiddling with some machines benchmarks of individual functions. See https://gist.github.com/michaelt/f19bef01423b17f29ffd The first list of results is hackage-pipes; the second is with these two repairs 
benchmarking drop/conduit
time                 26.56 ms   (26.31 ms .. 26.79 ms)
benchmarking drop/pipes
time                 43.64 ms   (42.48 ms .. 45.46 ms)
-- and with the modified drop:
benchmarking drop/pipes
time                 28.03 ms   (26.75 ms .. 29.67 ms)
Then 
benchmarking take/conduit
time                 45.38 ms   (44.57 ms .. 46.45 ms)
benchmarking take/pipes
time                 84.44 ms   (78.23 ms .. 91.36 ms)
and with the …

optimize take and drop

---

src/Pipes.hs
src/Pipes/Internal.hs

This was detected via the new
`-fwarn-noncanonical-monad-instances` warning

canonicalise Monad instances

---

src/Pipes/Tutorial.hs

There is no G, I believe you meant DEF instead of EFG.  While I was here, I also changed another example to consistently use DEF for out values instead of ABC.

Fix typo in example

---

src/Pipes/Tutorial.hs

It goes at a slower pace than "Monad Transformers - Step by Step", so for me as 
a Haskell beginner it was easier to understand. The chapters "Combining monads 
the hard way" and "Anatomy of a monad transformer" were particularly useful.

Mention "All About Monads" to help with understanding transformers

---

pipes.cabal

Currently, `pipes`' benchmarks fail to build on Hackage since `Common` isn't listed as `other-modules` of the benchmarks, which means `cabal sdist` doesn't package up `Common.hs` with the tarball.
See also https://github.com/fpco/stackage/issues/1372

Add Common.hs to other-modules in benchmarks

---

benchmarks/Common.hs
pipes.cabal
src/Pipes.hs
src/Pipes/Core.hs
src/Pipes/Internal.hs
src/Pipes/Prelude.hs

The rewrite rules defined in Pipes are currently quite fragile as the
functions which they match on may be inlined before the rules are given
an opportunity to fire. Here we delay inlining of various operations to ensure that the rules can fire
unimpeded during simplifier phase 2.
These cases are pointed out by a warning which will be introduced in GHC 8.0.1.

Delay inlining to allow rules to fire

---

.travis.yml
benchmarks/Common.hs
benchmarks/LiftBench.hs
pipes.cabal

This tests `pipes` across the last three GHC versions and also fixes issues identified by Travis (mostly in the benchmarks)

Add new Travis script

---

pipes.cabal
src/Pipes.hs
src/Pipes/Internal.hs

Also, given `MonadThrow` and `MonadCatch` instances for `Proxy`.

Several new instances for ListT

---

src/Pipes/Internal.hs

Previous version would accumulate the entire log unchanged, and then
append a modified version at the end; the new one removes the old log
entries by replacing them with `mempty`.
Here's an example (any `execWriter` from mtl):
```haskell
execWriter $ runEffect $ pass $ tell [1] >> pure ((), (2:))
```
Previously, this would evaluate to `[1,2,1]` (old log + modified old
log); now, it evaluates to `[2,1]`, same as when using just `WriterT`.

Fix `pass` in `MonadWriter` instance

---

src/Pipes.hs
src/Pipes/Core.hs
src/Pipes/Internal.hs
src/Pipes/Lift.hs
src/Pipes/Prelude.hs

This relaxes the Monad constraint for many functions using **Proxy** to Functor, throughout the library. The main places where this isn't possible are anything involving `runEffect`, or using `MonadTrans`, since `lift` requires a Monad constraint.
I also haven't touched the Tutorial module, because I'm not sure that it would make explaining things much easier to swap between Functor and Monad constraints.

Relax Monad constraints to Functor

---

pipes.cabal

This package doesn't build on GHC 7.8 or below today. This PR makes the base lower bound reflect that.
Alternatively, I think we could change the code to support below GHC 7.10 by doing things like replacing `<$>` with `liftM` and tweaking some constraints. If I wrote that pull request instead, would you be interested in that?

Update base lower bound so that we don't try to build on GHC < 7.10

---

pipes.cabal

`Pipes.Lift` is using `MFunctor (ExceptT e)` instances which were
added to mmorph in 1.0.4

Increase lower bound for mmorph to 1.0.4

---

src/Pipes/Prelude.hs

I'm guessing this is what it was meant to say, looks like a copy/paste issue from the `scan` documentation.

Correct documentation of scanM

---

pipes.cabal

They are not needed on newer GHC.

Depend on semigroups only on GHC < 8.0

---

src/Pipes.hs
src/Pipes/Prelude.hs

Fixes https://github.com/Gabriel439/Haskell-Pipes-Library/issues/224
It appears that we need to either eta-expand `yield` or move the
universal quantification to the outside.  The latter seems to be a more
robust solution.

GHC 9.0 support

---

src/Pipes.hs

This implements several of the documentation ideas I brought up in https://github.com/Gabriel439/Haskell-Pipes-Library/pull/184#issuecomment-825856215.
The present problem, I think, is that it is not obvious how to accomplish some basic `ListT` tasks (e.g. converting `ListT m a` to `m [a]`) unless you have the habit of knowing to convert to `Producer` first.
I also wanted to emphasize some of the things that you can do using just the typeclass instances.
I'm aiming to augment the `ListT` API documentation with just enough links and suggestions to serve as jumping-off points, without cluttering up the haddock page for the `Pipes` module too much.

Elaborate on the documentation for ListT

---

pipes.cabal

Related to https://github.com/commercialhaskell/stackage/issues/6122

Build against `mmorph-1.2.0`
